"""Inspect browser-ready prepared Kane-Map output layers.

The prepared address and building files can be large enough that full-file
``json.load`` inspection is wasteful on a small processing node. This module
streams the GeoJSON features array and records counts, geometry types, fields,
and top-level layer metadata.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any, Iterator

from .config import PREPARED_DIR, REPORTS_DIR

PREPARED_LAYER_INSPECTION_REPORT_PATH = REPORTS_DIR / "prepared_layer_inspection_report.json"


@dataclass(frozen=True)
class PreparedLayerInspection:
    layer_name: str
    file_name: str
    absolute_path: str
    exists: bool
    status: str
    bytes: int
    feature_count: int
    geometry_types: dict[str, int]
    property_fields: dict[str, int]
    kane_map_layer: dict[str, Any]
    sample_properties: list[dict[str, Any]]
    error: str | None = None


def now_utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def human_layer_name(path: Path) -> str:
    return path.stem


def _read_more(handle: Any, buffer: str, chunk_size: int) -> tuple[str, bool]:
    chunk = handle.read(chunk_size)
    if chunk == "":
        return buffer, True
    return buffer + chunk, False


def read_top_level_metadata(path: Path, chunk_size: int = 1024 * 1024) -> dict[str, Any]:
    """Read top-level metadata before the GeoJSON features array."""

    buffer = ""
    eof = False
    with path.open("r", encoding="utf-8") as handle:
        while True:
            buffer, eof = _read_more(handle, buffer, chunk_size)
            key_index = buffer.find('"features"')
            if key_index >= 0:
                prefix = buffer[:key_index].rstrip()
                if prefix.endswith(","):
                    prefix = prefix[:-1]
                payload = prefix + "}"
                try:
                    parsed = json.loads(payload)
                except json.JSONDecodeError:
                    return {}
                return parsed if isinstance(parsed, dict) else {}
            if eof:
                return {}
            if len(buffer) > chunk_size * 4:
                # The files generated by Kane-Map place features after metadata.
                # If this grows unexpectedly, stop trying to keep the prefix.
                return {}


def iter_geojson_features(path: Path, chunk_size: int = 1024 * 1024) -> Iterator[dict[str, Any]]:
    """Yield GeoJSON features one at a time from a FeatureCollection."""

    decoder = json.JSONDecoder()
    buffer = ""
    eof = False
    found_features = False

    with path.open("r", encoding="utf-8") as handle:
        while not found_features:
            buffer, eof = _read_more(handle, buffer, chunk_size)
            feature_key_index = buffer.find('"features"')
            if feature_key_index >= 0:
                array_index = buffer.find("[", feature_key_index)
                if array_index >= 0:
                    buffer = buffer[array_index + 1 :]
                    found_features = True
                    break
            if eof:
                raise ValueError("GeoJSON features array was not found")
            if len(buffer) > 256:
                buffer = buffer[-256:]

        while True:
            buffer = buffer.lstrip()
            if buffer.startswith(","):
                buffer = buffer[1:].lstrip()
            if buffer.startswith("]"):
                return

            while buffer == "" or (not buffer.startswith("{") and not buffer.startswith("]")):
                if eof:
                    raise ValueError("Unexpected end of file before next feature")
                buffer, eof = _read_more(handle, buffer, chunk_size)
                buffer = buffer.lstrip()
                if buffer.startswith(","):
                    buffer = buffer[1:].lstrip()
                if buffer.startswith("]"):
                    return

            while True:
                try:
                    feature, end_index = decoder.raw_decode(buffer)
                    break
                except json.JSONDecodeError:
                    if eof:
                        raise
                    buffer, eof = _read_more(handle, buffer, chunk_size)

            if isinstance(feature, dict):
                yield feature
            else:
                yield {"type": "invalid_feature", "properties": {}, "geometry": None}
            buffer = buffer[end_index:]


def inspect_feature_collection(path: Path, sample_limit: int) -> tuple[int, dict[str, int], dict[str, int], list[dict[str, Any]]]:
    geometry_types: Counter[str] = Counter()
    property_fields: Counter[str] = Counter()
    sample_properties: list[dict[str, Any]] = []
    feature_count = 0

    for feature in iter_geojson_features(path):
        feature_count += 1

        geometry = feature.get("geometry")
        if isinstance(geometry, dict):
            geometry_type = geometry.get("type")
            geometry_types[str(geometry_type or "missing_type")] += 1
        elif geometry is None:
            geometry_types["null"] += 1
        else:
            geometry_types["invalid_geometry"] += 1

        properties = feature.get("properties")
        if isinstance(properties, dict):
            property_fields.update(str(key) for key in properties.keys())
            if len(sample_properties) < sample_limit:
                sample_properties.append(properties)
        else:
            property_fields["invalid_properties"] += 1

    return (
        feature_count,
        dict(sorted(geometry_types.items())),
        dict(sorted(property_fields.items())),
        sample_properties,
    )


def inspect_prepared_layer(path: Path, sample_limit: int = 3) -> PreparedLayerInspection:
    layer_name = human_layer_name(path)

    if not path.exists():
        return PreparedLayerInspection(
            layer_name=layer_name,
            file_name=path.name,
            absolute_path=str(path),
            exists=False,
            status="missing",
            bytes=0,
            feature_count=0,
            geometry_types={},
            property_fields={},
            kane_map_layer={},
            sample_properties=[],
        )

    if path.suffix.lower() != ".json":
        return PreparedLayerInspection(
            layer_name=layer_name,
            file_name=path.name,
            absolute_path=str(path),
            exists=True,
            status="unsupported",
            bytes=path.stat().st_size,
            feature_count=0,
            geometry_types={},
            property_fields={},
            kane_map_layer={},
            sample_properties=[],
            error="prepared inspection supports .json files only",
        )

    try:
        top_level = read_top_level_metadata(path)
        kane_map_layer = top_level.get("kane_map_layer", {})
        if not isinstance(kane_map_layer, dict):
            kane_map_layer = {}
        feature_count, geometry_types, property_fields, sample_properties = inspect_feature_collection(path, sample_limit)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        return PreparedLayerInspection(
            layer_name=layer_name,
            file_name=path.name,
            absolute_path=str(path),
            exists=True,
            status="error",
            bytes=path.stat().st_size,
            feature_count=0,
            geometry_types={},
            property_fields={},
            kane_map_layer={},
            sample_properties=[],
            error=str(exc),
        )

    return PreparedLayerInspection(
        layer_name=layer_name,
        file_name=path.name,
        absolute_path=str(path),
        exists=True,
        status="ok",
        bytes=path.stat().st_size,
        feature_count=feature_count,
        geometry_types=geometry_types,
        property_fields=property_fields,
        kane_map_layer=kane_map_layer,
        sample_properties=sample_properties,
    )


def prepared_layer_files(prepared_dir: Path = PREPARED_DIR) -> list[Path]:
    if not prepared_dir.exists():
        return []
    return sorted(path for path in prepared_dir.glob("*.json") if path.is_file())


def inspect_prepared_layers(
    selected_layers: set[str] | None = None,
    sample_limit: int = 3,
    prepared_dir: Path = PREPARED_DIR,
) -> list[PreparedLayerInspection]:
    selected = selected_layers or set()
    results: list[PreparedLayerInspection] = []
    for path in prepared_layer_files(prepared_dir):
        layer_name = human_layer_name(path)
        if selected and layer_name not in selected and path.name not in selected:
            continue
        results.append(inspect_prepared_layer(path, sample_limit=sample_limit))
    return results


def write_prepared_layer_inspection_report(
    inspections: list[PreparedLayerInspection],
    report_path: Path = PREPARED_LAYER_INSPECTION_REPORT_PATH,
) -> None:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "report_type": "prepared_layer_inspection",
        "inspection_mode": "streaming_geojson",
        "generated_at": now_utc(),
        "counts": {
            "files": len(inspections),
            "ok": sum(1 for item in inspections if item.status == "ok"),
            "errors": sum(1 for item in inspections if item.status == "error"),
            "unsupported": sum(1 for item in inspections if item.status == "unsupported"),
            "total_bytes": sum(item.bytes for item in inspections),
            "total_features": sum(item.feature_count for item in inspections),
        },
        "layers": [asdict(item) for item in inspections],
    }
    report_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
