(function kaneMapDomReferences(global) {
  "use strict";

  function createDomReferences() {
    return {
      selectedCell: document.getElementById("selectedCell"),
      selectedBuilding: document.getElementById("selectedBuilding"),
      selectedStories: document.getElementById("selectedStories"),
      buildingSummary: document.getElementById("buildingSummary"),
      identitySummary: document.getElementById("identitySummary"),
      observationForm: document.getElementById("observationForm"),
      observationFormTitle: document.getElementById("observationFormTitle"),
      editModeNotice: document.getElementById("editModeNotice"),
      saveObservation: document.getElementById("saveObservation"),
      cancelEdit: document.getElementById("cancelEdit"),
      clearObservationFormButton: document.getElementById("clearObservationFormButton"),
      visitDate: document.getElementById("visitDate"),
      fieldSessionId: document.getElementById("fieldSessionId"),
      planPriority: document.getElementById("planPriority"),
      planAction: document.getElementById("planAction"),
      siteLabel: document.getElementById("siteLabel"),
      buildingAlias: document.getElementById("buildingAlias"),
      entranceId: document.getElementById("entranceId"),
      mailboxBankId: document.getElementById("mailboxBankId"),
      visibleDesignators: document.getElementById("visibleDesignators"),
      designatorPreview: document.getElementById("designatorPreview"),
      unitCount: document.getElementById("unitCount"),
      designatorPattern: document.getElementById("designatorPattern"),
      confidence: document.getElementById("confidence"),
      visitStatus: document.getElementById("visitStatus"),
      accessContext: document.getElementById("accessContext"),
      observationNotes: document.getElementById("observationNotes"),
      showSelectedOnly: document.getElementById("showSelectedOnly"),
      recordCount: document.getElementById("recordCount"),
      recordList: document.getElementById("recordList"),
      storageStatus: document.getElementById("storageStatus"),
      viewStatus: document.getElementById("viewStatus"),
      chunkStatus: document.getElementById("chunkStatus"),
      visibleCellStatus: document.getElementById("visibleCellStatus"),
      reviewFilterStatus: document.getElementById("reviewFilterStatus"),
      visitStatusSummary: document.getElementById("visitStatusSummary"),
      zoomIn: document.getElementById("zoomIn"),
      zoomOut: document.getElementById("zoomOut"),
      prevBuilding: document.getElementById("prevBuilding"),
      nextBuilding: document.getElementById("nextBuilding"),
      resetView: document.getElementById("resetView"),
      copySelection: document.getElementById("copySelection"),
      navSearch: document.getElementById("navSearch"),
      clearSearch: document.getElementById("clearSearch"),
      searchResults: document.getElementById("searchResults"),
      coverageSummary: document.getElementById("coverageSummary"),
      statusFilter: document.getElementById("statusFilter"),
      coverageByCell: document.getElementById("coverageByCell"),
      visitSessionSummary: document.getElementById("visitSessionSummary"),
      fieldPlanSummary: document.getElementById("fieldPlanSummary"),
      planFilter: document.getElementById("planFilter"),
      fieldPlanRows: document.getElementById("fieldPlanRows"),
      planStatusSummary: document.getElementById("planStatusSummary"),
      shortcutStatus: document.getElementById("shortcutStatus"),
      visitSessionRows: document.getElementById("visitSessionRows"),
      chooseSectorFolder: document.getElementById("chooseSectorFolder"),
      saveSectorStateNow: document.getElementById("saveSectorStateNow"),
      autosaveThreshold: document.getElementById("autosaveThreshold"),
      sectorCurrentStatus: document.getElementById("sectorCurrentStatus"),
      sectorFolderStatus: document.getElementById("sectorFolderStatus"),
      sectorJournalStatus: document.getElementById("sectorJournalStatus"),
      sectorPendingStatus: document.getElementById("sectorPendingStatus"),
      sectorLastWriteStatus: document.getElementById("sectorLastWriteStatus"),
      sectorStorageMessage: document.getElementById("sectorStorageMessage"),
      clearRecords: document.getElementById("clearRecords"),
      workspaceTabs: Array.from(document.querySelectorAll(".workspace-tab")),
      workspacePanels: Array.from(document.querySelectorAll("[data-tab-panel]")),
      selectedWorkspaceHeader: document.getElementById("selectedWorkspaceHeader")
    };
  }

  global.KaneMapDomReferences = { createDomReferences };
})(window);
